### ISSUE TITLE
how to put float/double into hmap?

### ISSUE THREAD

**Issue by Chalno** [faragon/libsrt#21]
there is no float/double value in hashmap

**Comment by faragon** [comment]
Hi @Chalno, I'll add float and double support to all data types using numbers (vector, map, set, hash map, and hash set). I'll add it soon (haven't added it before because the need was not identified/requested). Thank you :-)

P.S. Plan:

Hash map and map: add Float-Float, and Double-Double maps.
Hash set and set: add Float and Double sets
Vector: add Float and Double types.

**Comment by Chalno** [comment]
thank you!

**Comment by faragon** [comment]
PR #28 merged to master. Floating support (float and double) added for vectors, maps, sets, hash maps, and hash sets.
