### ISSUE TITLE
How to convert int to srt_string*?

### ISSUE THREAD

**Issue by drkameleon** [faragon/libsrt#23]
Given an `int`(32 bit signed int), what is the most efficient (see: fastest) way to convert it to an srt_string?

Thanks in advance!

**Comment by drkameleon** [comment]
Answering my own question (I think):

```
int k  = 10;
srt_string* str = ss_dup_int(k);
```

**Comment by faragon** [comment]
@drkameleon there is a more efficent way, using stack allocation, e.g.

**Comment by faragon** [comment]
@drkameleon there is a more efficent way, using stack allocation (_ss\_dup\_*_ does heap llocation, and it requires further _ss\_free_), e.g. with both _ss\_*\_int_ and _ss\_sprintf_:
```                                                      
void example1()
{
        srt_string *s;
        size_t smax = 128;

        s = ss_alloca(smax);
        ss_cpy_int(&s, 123);

        fprintf(stderr, "s: %s\n", ss_to_c(s));
}

void example2()
{
        srt_string *s;
        size_t smax = 128;

        s = ss_alloca(smax);
        ss_printf(&s, smax, "%i\n", 456);

        fprintf(stderr, "s: %s\n", ss_to_c(s));
}
```

**Comment by drkameleon** [comment]
Thanks again for such a thorough explanation!

Your example (combining the two - printing *and* converting in the same function) shows the right direction I should take myself I think.

One question I still have is whether I could (safely) use ss_alloca and just *return* the string from that `example1` function (instread of directly printing it, that is).

**What it's all about:**

_For the past 5 months, I've been working on a new programming language + bytecode interpreter (Arturo, you cannot find it in my repos, although not the current version yet, just an AST walking interpreter), and  trying different implementation languages. I started with D, moved to Nim, and given that my #1 priority is speed, I rather obviously ended up in C. So I now find myself experimenting with different C libraries, covering mainly strings, arrays and hash maps... and I think the only that so far works well for me is your library :)_

**Comment by faragon** [comment]
For retrieving results from a function, while avoiding unnecessary copies and allocations, I recommend you using a double pointer parameter, passing a reusable "scratchpad" strings. It is faster to reuse strings, as resize is free. E.g.
```
int my_function(srt_string **output, srt_string **tmp1, srt_string **tmp2, /* ... other input parameters here*/)
{
      /* ss_clear() for output/tmp1/tmp2, etc. */
}
```
Yesterday I saw your Arturo project, very nice (haven't heard about the Nim language before, interesting the thing of having C as output). Regarding hash maps \-and maps\-, the ones in the 'libsrt' library include short-string optimization, which is very efficient for keys below 49 bytes (string-string hash map, below 19 bytes for string-int) (strings directly in the hash map buckets \-in the map tree node in the case of using maps, instead of hash maps\-, see src/saux/sstringo.h), so string-string hash maps \-and also string-string maps\- are both fast and have a small memory footprint. If you need the last bit of performance, you could use just the hash-map stuff as example, e.g. writing your own custom implementation. Check src/shmap.c for a linear-addressing hash example, with decoupled hash function <-> bucket id, with optimized resize that avoids unnecesary data movement:
```
        /*                                                                      
         * Memory map:                                                          
         * | headerA | buckets #A |    data #A    |                             
         * <-- hs0 -->            <----- sxzm ---->                             
         * <--------- hs1 -------->                                             
         *                                                                      
         * | headerB | buckets #B = 2 * b#A |    data #B    |                   
         * <-- hs0 -->                      <----- sxzm ---->                   
         * <---------------- hs2 ----------->                                   
         *                        <-- ds1 -->                                   
         *                                  <-ds2->                             
         *                                        <-- ds1'-->                   
         */                                                                     
        /* move ds1 from the head, to the tail */                               
```

**Comment by drkameleon** [comment]
Thanks a lot! I'll keep that in mind. Especially your suggestion about strings sounds very sensible. I'll experiment with that as well.

Regarding Nim, I discovered it a couple of months ago. It's very interesting project and with very good performance (the compiler actually outputs highly-optimized C code).

However, the problem comes when you need to have even more control over things (and in my case, I do obviously need total control) which means that I ended up applying "hacks" to get things working as I wanted. Plus, the community is a bit weird for my taste... I mean, although generally active and helpful, it's not uncommon to get some arrogant remark (because I guess everybody is too stupid to understand what should have been better documented in the first place).

All in all, I think it's worth giving it a try. ;-)
