### ISSUE TITLE
How to efficiently print an srt_string*?

### ISSUE THREAD

**Issue by drkameleon** [faragon/libsrt#24]
What I'm doing right now:

```c
srt_string* srt = ss_dup_c("some string");
printf("the string is: %s\n", ss_to_c(srt));
```

**Comment by faragon** [comment]
Hi @drkameleon, the _ss\_dup\_c()_ involves heap allocation, requiring further deallocation, with _ss\_free()_ (internally does one call to _malloc()_ and one to _free()_ -C library, with from 0 to 2 OS trap calls, depending on the allocation pool-). The call to _ss\_to\_c()_ is O(1), while the call to "printf" would typically involve one 0 to 1 OS trap calls (_printf()_ is buffered, so not always translated to one OS trap call).

```
void example1()
{
        srt_string* srt = ss_dup_c("some string");
        printf("the string is: %s\n", ss_to_c(srt));
        ss_free(&srt);
}                                                                               
```

If you don't need to modify the data, you can use _ss\_crefa()_ instead of the "dup" function, involving zero heap usage and zero copy (it uses a very small amount of memory on the stack for allocating the reference to the original string), e.g. 
```
void example2()
{
        const srt_string* srt = ss_crefa("some string");
        printf("the string is: %s\n", ss_to_c(srt));
}                                                                               
```

**Comment by faragon** [comment]
In the future I'll probably add a full implementation of sprintf supporting the "srt" strings, just for fun, so the formatting can be done avoiding _strlen()_ calls (in the same way of _ss\_cat*()_ work, doing just one resize no matter the number of parameters given).

**Comment by drkameleon** [comment]
Thanks a lot for your answer!

And thanks for making clear the use of `ss_crefa` (I've played with it but wasn't 100% what the caveats were).
